[project]
name = "afterhours_papers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "tinygrad",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0",
]

[project.optional-dependencies]
dev = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "mypy>=1.15.0",
    "ruff>=0.11.4",
    "unicodeplots",
    "uv>=0.6.13",
    "wandb>=0.19.9",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
torchvision = [
  { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
unicodeplots = { git = "https://github.com/GalaxAI/unicodeplot-py.git" }
tinygrad = {git = "https://github.com/tinygrad/tinygrad.git"}

  [[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.2.4"
